### ISSUE TITLE
Full-screen maps prevents scrolling

### ISSUE THREAD

**Issue by holograph** [scalaspace/scalaspace.github.io#1]
When scrolling with mousewheel, touchpad or similar, the map takes the focus and instead zooms (this appears to be the default behaviour with every browser I tried), which means you can't get to the text at the bottom without resorting to keyboard controls. We should probably add a significant margin (at least 20% screen space) around the map to allow for scrolling.

**Comment by utaal** [comment]
Yep, experienced this as well (actually, I initially didn't realize there was text at the bottom as the map extended beyond the bottom of the page). Why don't you just move the box in the top-right corner where there's plenty of room?

**Comment by utaal** [comment]
I tried, it doesn't look too good, and it's hard to make the text fit: https://github.com/utaal/scalaspace.github.io/tree/corner-box

**Comment by propensive** [comment]
In time there will probably be more stuff on the page, beneath the map, so I think the solution needs to "fix" scrolling. For now, the best solution may be to do what @holograph suggested and add some margin.

**Comment by stefanobaghino** [comment]
What would you think of restyling the site to have a full-screen map, adding content through popups? I've tried to make an example here. https://github.com/stefanobaghino/scalaspace.github.io/tree/sb_issue1_style_experiment

**Comment by propensive** [comment]
Fixed, thanks to @stefanobaghino.
