### ISSUE TITLE
Default focus to world

### ISSUE THREAD

**Issue by rajmahendra** [scalaspace/scalaspace.github.io#52]
Currently when user land to scala.space, the focus of the map is given somewhere to Germany.

If we can show the whole world map it will be good. 
Yes the markers may be hidden but it can show total markers in each continent .

**Comment by jarrodu** [comment]
I like this idea. Lets see what it will take. I will add it to a Milestone for now. I think we can so issue #64 at the same time.

**Comment by jarrodu** [comment]
fixed by dd4da702455c7cf38190c498b511e12649bac7aa

**Comment by SethTisue** [comment]
great to see all these improvements landing... the map looks really good

**Comment by jarrodu** [comment]
Thanks Seth. I should do a writeup on our future plans. There are some unsolved problems that I think we can tackle. For instance, I think it should be easier for meetups to see what other meetups are doing. This could lead to inspiration and maybe even healthy competition.  

I have also been doing some data analysis using Meetups API and it seems like there are some interesting patterns. At some point soon I am hoping to transform these insights into actionable recommendations.
