### ISSUE TITLE
center map in user location

### ISSUE THREAD

**Issue by anicolaspp** [scalaspace/scalaspace.github.io#64]
When open the map, it should be centered based on the user browser location. If I am in Miami, USA, the map should be centered here instead of London when it is opened the first time.

**Comment by SethTisue** [comment]
either that or it should be centered on the current whereabouts of @propensive ;-)

**Comment by rajmahendra** [comment]
I am getting London, but i am from India :)

**Comment by propensive** [comment]
If it's centred on me, then London is almost exactly 10000km out...

**Comment by jarrodu** [comment]
To get this working we have to serve the site over TLS. I will try to get this working now that GitHub pages supports it.

**Comment by jarrodu** [comment]
I am closing this because it does not make as much sense now that we are starting the page zoomed all the way out.
